### ISSUE TITLE
Profile Sections not updating

### ISSUE THREAD

**Issue by Bony5690** [SolveSmartCities/SolveSmartCities.App#129] opened 2017-07-08 02:07 UTC
Personal Info section updates when making changes to a clients profile, but the rest of the sections afterward do not update after making changes. The changes are not reflected from the view neither.

**Comment by reidcompton** [comment] 2017-07-08 18:50
@Bony5690 -- Could you include some steps to reproduce this? i.e. which type of user you were logged in as, which page you attempted to edit, what edits you were trying to make, and where you observed that the change did not happen. That'll help me understand the issue and how to fix it.

**Comment by Bony5690** [comment] 2017-07-09 00:48
1. Logged in as a service provider
2. Click Clients Tab
3. Click view to open dropdown client tab
4.Click edit profile
5. Tried to edit client profile and was not able to edit and update any section except personal info section.

**Comment by reidcompton** [comment] 2017-07-10 13:49
I'm not able to reproduce this as described. I followed steps 1-3, and then I went into the Family section and successfully added a family member.

Could you describe a specific page that you are trying to edit, which data you are trying to add/change, and the result?

**Comment by Bony5690** [comment] 2017-07-10 14:11
its from the staging site not the localhost, I was not able to make any edits to the profile except for the personal info section

**Comment by reidcompton** [comment] 2017-07-10 14:19
Just tested on staging, was able to add a family member there too.
Can you give me the exact steps to reproduce, including the login credentials for the account that you are using, the page you are not able to edit (pick one), the data that you are trying to add?

**Comment by Bony5690** [comment] 2017-07-10 14:23
username: jerrybony@yahoo.com
password: Bony5690

1. log in as a service provider
2. Click view on Jenkins client
3. Click edit on family section and try to make an edit. After I make the change and I click submit the changes are not reflected in the view.

**Comment by reidcompton** [comment] 2017-07-10 14:27
Ok, I see what I was doing wrong. Adding  on those pages works, but editing existing family members, schools, jobs, don't update. You are correct sir :)

**Comment by Bony5690** [comment] 2017-07-10 14:35
I have the similar issue when logged in as a localhost44352

**Comment by reidcompton** [comment] 2017-07-10 14:53
Yep. The code as written now is basically checking to see if a family member exists (or school, job, etc), and if not, adding it, if it does exist, skipping it. This should be fixed to update the details too.

**Closed** 2017-07-31 21:53 UTC
Labels: bug
